### ISSUE TITLE
Commits 4ca5cae broke EHPTlib.MapBased.TestingModels.TestIceConn

### ISSUE THREAD

**Issue by casella** [ceraolo/EHPTlib#2]
According to this [regression report](https://libraries.openmodelica.org/branches/history/master/2023-10-23%2023:17:30..2023-10-24%2023:40:02.html), model EHPTlib.MapBased.TestingModels.TestIceConn stopped working between Oct 23 and Oct 24, giving the following error:
```
[EHPTlib 2.1.4-main/MapBased/TestingModels.mo:107:34-107:62:writable]
Error: Modified element mapsFileName not found in class IceConnP.
```
The root cause is commit 4ca5cae, which replaced PartialMBiceP with PartialIceP, that unfortunately doesn't contain the mapsOnFile parameter.

**Comment by ceraolo** [comment]
This was my fault. It was fixed a few days after this ticket was opened.
